"""
Django settings for qneeproject project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib import messages

# 24/07/16 日付入力フォーマットを追加するために追加 
from django.conf.global_settings import DATETIME_INPUT_FORMATS, DATE_INPUT_FORMATS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

PROJECT_NAME = os.path.basename(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'accounts.apps.AccountsConfig',
  'qpay.apps.QpayConfig',
  'send.apps.SendConfig',

  'django_bootstrap5',
  'django_bootstrap_icons',
  'django.contrib.humanize',
  'contact',
  'django_celery_beat', # 260328に追加（celery, django-celery-beat, redisをinstall）
  #'django.contrib.sites',
  #'allauth',
  #'allauth.account',
  #'allauth.socialaccount',
]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
  #'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'qneeproject.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [
      BASE_DIR / 'templates',
      BASE_DIR / 'qneeproject/templates',
    ],    #24/03/20

    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'qneeproject.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'      # 24/03/20 デフォルト値は'en-us'
TIME_ZONE = 'Asia/Tokyo'  # 24/03/20 デフォルト値は'UTC'

USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# リクエストURLが/static/で始まるときに静的ファイルを返す
# テンプレートで"{% static  '*.jpg' %}"でURLを作成できる

STATIC_ROOT = '/var/www/{}/static'.format(PROJECT_NAME)
# 集約用の管理コマンド「manage.py collectstatic」を実行した時に、
# staticファイルがコピーされるディレクトリのパス
# 本番環境でリバースプロキシを立ち上げたときに参照しにいくところ（外から見るとき） 24/11/23

print(f'STATIC_ROOTは、{STATIC_ROOT}')

STATICFILES_DIRS = [
  os.path.join(BASE_DIR, 'qneeproject/static/'),
  #os.path.join(BASE_DIR, 'static/')
] # django.contrib.staticfilesをINSTALLED APPSに加える必要あり

MEDIA_URL = '/media/'              # 240414 追加　本人確認や請求書の画像アップロード用
MEDIA_ROOT = '/var/www/{}/media'.format(PROJECT_NAME)    
# 240414追加  本人確認や請求書の画像アップロード用、241124パス変更（現場で使えるDjangoの教科書p148に従う）
# staticファイルはデフォルトでは、アプリ下のstaticフォルダからしか読み取れない
# ここで個別に指定することで読み込めるようにする


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#認証関連の設定
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    #'accounts.backends.auth_backends.AuthenticationBackend',
]

#ACCOUNT_LOGOUT_REDIRECT_URL = 'accounts/login'
#ACCOUNT_EMAIL_VERIFICAION = 'mandatory'
#ACCOUNT_EMAIL_REQUIRED = True  # ユーザー登録画面の必須項目に
#ACCOUNT_AUTHENTICATION_METHOD = 'email'
#ACCOUNT_USERNAME_REQUIRED = False
#SITE_ID = 1

AUTH_USER_MODEL = 'accounts.CustomUser' 

# 24/03/20追加  LovinView.view_asの内の「redirect_authenticated_user=True」に対応
LOGIN_REDIRECT_URL = 'accounts:login_redirect'
# LOGIN_URL = '' # '/'
# 未ログイン時に遷移するURL
# 本来ログイン後で確認できるページに無断でアクセスされない為にも設定しておく必要があります。  

# 24/03/23追加
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' #デフォルト値のため省略可
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'shuichiro4'
EMAIL_HOST_PASSWORD = 'ddkn sicy prrt tkea'
DEFAULT_FROM_EMAIL = 'shuichiro4@gmail.com'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# 24/05/13追加 これを加える前提として利用規約を表示させるため
X_FRAME_OPTIONS = 'SAMEORIGIN'

# 24/05/28に追加、IntegerFieldをカンマ表示にするため
NUMBER_GROUPING = 3

# 24/06/13に追加
MESSAGE_TAGS = {
  messages.INFO: 'alert alert-info',
  messages.SUCCESS: 'alert alert-success',
  messages.WARNING: 'alert alert-warning',
  messages.ERROR: 'alert alert-danger',
}

# 24/07/16 日付入力フォーマットを追加
DATE_INPUT_FORMATS += ('%Y/%m/%d',)
DATETIME_INPUT_FORMATS += [
  '%Y/%m/%d',
  '%Y/%m/%d %H:%M:%S',
]

DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': 'qnee_db',
    'USER': 'shuichiro',
    'PASSWORD': '921Story552@',
    'HOST': 'localhost',
    'PORT': '5432',     # PostgreSQLのデフォルトポート
    'OPTIONS': {
      'options': '-c search_path=public'  # ここを確認・追加
    },
  }
}

# Celeryの設定
CELERY_BROKER_URL = 'redis://localhost:6379/0' # RedisのURL
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tokyo' # タイムゾーン

from celery.schedules import crontab


# 定期タスクのスケジュールを設定 (beat)
# 260329 完成したらProductionにもコピーすｒ
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
#CELERY_BEAT_SCHEDULE = {
#    'sayHello': {
#        'task': 'send.tasks.add',
#        'schedule': crontab(),  # execute every minute
#        'args': (1, 1),     
#    }
#}

# CELERYD_LOG_FILE = "./celeryd.log"
