# Generated by Django 5.1.2 on 2026-07-01 13:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import qpay.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_remove_bankaccount_entity_id_bankaccount_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanceTerm_YYYYMM', models.CharField(blank=True, max_length=6, null=True, verbose_name='前払い年月')),
                ('status', models.CharField(default='notDone', max_length=6, verbose_name='清算状況')),
                ('clearedAmount', models.IntegerField(null=True, verbose_name='清算金額（円）')),
                ('cleared_at', models.DateTimeField(default=None, verbose_name='清算日')),
                ('buyEntity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.legalentity', verbose_name='パートナー')),
            ],
        ),
        migrations.CreateModel(
            name='QpayTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellEntityname', models.CharField(blank=True, max_length=150, verbose_name='ゲスト・エンティティ名')),
                ('sellUser_personname', models.CharField(max_length=150, verbose_name='ゲスト・ユーザー名')),
                ('buyEntityname', models.CharField(blank=True, default='', max_length=150, verbose_name='パートナー・エンティティ名')),
                ('buyUser_personname', models.CharField(max_length=150, null=True, verbose_name='ゲスト・ユーザー名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='データ作成時点')),
                ('requested_at', models.DateTimeField(null=True, verbose_name='ご申請時点')),
                ('requested_amount', models.IntegerField(verbose_name='ご申請金額（円）')),
                ('exPayment_date', models.DateField(null=True, verbose_name='当初報酬日')),
                ('evidence', models.FileField(default=None, null=True, upload_to=qpay.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])], verbose_name='ご報酬の証明（請求書など）')),
                ('txStatus', models.IntegerField(choices=[(0, 'Unprocessed'), (1, 'Under Application'), (2, 'Buyer Pending'), (3, 'Buyer Approved'), (4, 'Qnee Pending'), (5, 'Qnee Payed'), (6, 'Buyer Payed'), (-3, 'Buyer Disapproved'), (-5, 'Qnee Disapproved')], default=1, verbose_name='処理状況 No')),
                ('txStatus_char', models.CharField(default='未処理', max_length=20, verbose_name='処理状況')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認時点')),
                ('approved_amount', models.IntegerField(null=True, verbose_name='承認金額（円）')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='否認時点')),
                ('advanced_at', models.DateTimeField(blank=True, null=True, verbose_name='前払い時点')),
                ('advance_amount', models.IntegerField(default=0, verbose_name='前払い予定額')),
                ('advance_fee', models.IntegerField(default=0, verbose_name='前払い手数料')),
                ('referral_fee', models.IntegerField(default=0, verbose_name='ご報酬（紹介料）')),
                ('transfer_fee', models.IntegerField(default=0, verbose_name='振込手数料')),
                ('total_fee', models.IntegerField(default=0, verbose_name='合計手数料')),
                ('transfer_amount', models.IntegerField(default=0, verbose_name='送金額')),
                ('buyEntity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyEntity_txs', to='accounts.legalentity', verbose_name='パートナー・エンティティ')),
                ('buyUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyUser_txs', to=settings.AUTH_USER_MODEL, verbose_name='パートナー・ユーザー')),
                ('clearingInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearingInfo_qpaytx', to='qpay.clearinginfo', verbose_name='最新清算リンク')),
                ('sellEntity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellEntity_txs', to='accounts.legalentity', verbose_name='ゲスト・エンティティ')),
                ('sellUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellUser_txs', to=settings.AUTH_USER_MODEL, verbose_name='ゲスト・ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='SendbackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='差戻時点')),
                ('type1_frWho', models.IntegerField(blank=True, choices=[(1, 'パートナー'), (3, 'Qnee')], default=None, null=True)),
                ('status', models.IntegerField(choices=[(-1, 'History'), (1, 'After Sendback'), (2, 'After Response')], default=1, verbose_name='処理状況 No')),
                ('reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='差戻理由')),
                ('message', models.TextField(blank=True, max_length=200, null=True, verbose_name='差戻理由')),
                ('qpaytx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qpay.qpaytx', verbose_name='QPAY取引')),
            ],
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='sendbackInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendbackInfo_qpaytx', to='qpay.sendbackinfo', verbose_name='最新差戻リンク'),
        ),
    ]
