# Generated by Django 5.1.2 on 2025-02-12 20:30

import django.core.validators
import django.db.models.deletion
import qpay.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QpayTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.EmailField(max_length=254, null=True, verbose_name='受注者メールアドレス')),
                ('seller_personname', models.CharField(max_length=150, null=True, verbose_name='受注者ユーザー名')),
                ('seller_entityname', models.CharField(blank=True, max_length=150, null=True, verbose_name='受注者エンティティ名')),
                ('buyer_email', models.EmailField(max_length=254, null=True, verbose_name='パートナー・email')),
                ('buyer_personname', models.CharField(max_length=150, null=True, verbose_name='パートナー・ユーザー名')),
                ('buyer_entityname', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='パートナー・エンティティ名')),
                ('buyer_entity_choice', models.IntegerField(default=1, verbose_name='お支払者')),
                ('requested_at', models.DateTimeField(default=None, null=True, verbose_name='ご申請時点')),
                ('requested_amount', models.IntegerField(default=None, null=True, verbose_name='ご申請金額（円）')),
                ('approved_amount', models.IntegerField(default=None, null=True, verbose_name='承認金額（円）')),
                ('original_payment_date', models.DateTimeField(default=None, null=True, verbose_name='報酬日')),
                ('advanced_payment_date', models.DateTimeField(default=None, null=True, verbose_name='前払日')),
                ('evidence', models.FileField(null=True, upload_to=qpay.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])], verbose_name='ご報酬の証明（請求書など）')),
                ('tx_status_int', models.IntegerField(choices=[(1, 'Unprocessed'), (2, 'Approved'), (3, 'Disapproved'), (4, 'Qnee Payed'), (5, 'Buyer Payed')], default=1, verbose_name='処理状況 No')),
                ('tx_status_char', models.CharField(default='承認待ち', max_length=20, verbose_name='処理状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='データ作成時点')),
                ('approved_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='承認時点')),
                ('rejected_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='否認時点')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時点')),
                ('advance_amount', models.IntegerField(default=0, verbose_name='立替金額')),
                ('advance_fee', models.IntegerField(default=0, verbose_name='立替手数料')),
                ('referral_fee', models.IntegerField(default=0, verbose_name='ご報酬（紹介料）')),
                ('transfer_fee', models.IntegerField(default=0, verbose_name='振込手数料')),
                ('total_fee', models.IntegerField(default=0, verbose_name='合計手数料')),
                ('to_seller_amount', models.IntegerField(default=0, verbose_name='振込金額')),
                ('buyer_entity', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_tx', to='accounts.legalentity', verbose_name='パートナー・エンティティ')),
                ('buyer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_buyerUser', to=settings.AUTH_USER_MODEL, verbose_name='発注者ユーザー')),
                ('seller_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_sellerEntity', to='accounts.legalentity', verbose_name='受注者エンティティ')),
                ('seller_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_sellerUser', to=settings.AUTH_USER_MODEL, verbose_name='受注者ユーザー')),
            ],
        ),
    ]
