# Generated by Django 5.1.2 on 2026-06-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyUser_personname',
            new_name='buyUser_username',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellUser_personname',
            new_name='sellUser_username',
        ),
    ]
