# Generated by Django 5.1.2 on 2025-02-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='advanced_payment_date',
            field=models.DateField(default=None, null=True, verbose_name='前払日'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='original_payment_date',
            field=models.DateField(default=None, null=True, verbose_name='報酬日'),
        ),
    ]
