# Generated by Django 5.1.2 on 2026-03-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='txStatus_int',
            field=models.IntegerField(choices=[(1, 'Unprocessed'), (2, 'Buyer Approved'), (3, 'Buyer Disapproved'), (4, 'Qnee Payed'), (5, 'Qnee Unpayed'), (6, 'Buyer Payed')], default=1, verbose_name='処理状況 No'),
        ),
    ]
