# Generated by Django 5.1.2 on 2026-07-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='sellUser_personname',
            field=models.CharField(max_length=150, null=True, verbose_name='ゲスト・ユーザー名'),
        ),
    ]
