# Generated by Django 5.1.2 on 2025-02-15 00:43

import django.core.validators
import qpay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0002_alter_qpaytx_advanced_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='evidence',
            field=models.FileField(default=None, null=True, upload_to=qpay.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])], verbose_name='ご報酬の証明（請求書など）'),
        ),
    ]
