# Generated by Django 5.1.2 on 2026-03-16 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0002_alter_qpaytx_txstatus_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='データ作成時点'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新時点'),
        ),
    ]
