# Generated by Django 5.1.2 on 2025-05-03 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_type1_alter_customuser_type2_and_more'),
        ('qpay', '0003_alter_qpaytx_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpaytx',
            name='seller_email',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='seller_personname',
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='seller_user_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='ゲスト・メールアドレス'),
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='seller_user_personname',
            field=models.CharField(max_length=150, null=True, verbose_name='ゲスト・ユーザー名'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyer_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='パートナー・メールアドレス'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_buyerUser', to=settings.AUTH_USER_MODEL, verbose_name='パートナー・ユーザー'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='seller_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_sellerEntity', to='accounts.legalentity', verbose_name='ゲスト・エンティティ'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='seller_entityname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ゲスト・エンティティ名'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='seller_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_sellerUser', to=settings.AUTH_USER_MODEL, verbose_name='ゲスト・ユーザー'),
        ),
    ]
