# Generated by Django 5.1.2 on 2026-07-03 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0004_alter_qpaytx_approved_amount_alter_qpaytx_txstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='clearingInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearingInfo_qpaytx', to='qpay.clearinginfo', verbose_name='最新清算リンク'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sendbackInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendbackInfo_qpaytx', to='qpay.sendbackinfo', verbose_name='最新差戻リンク'),
        ),
        migrations.AlterField(
            model_name='sendbackinfo',
            name='qpaytx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qpay.qpaytx', verbose_name='QPAY取引'),
        ),
    ]
