# Generated by Django 5.1.2 on 2025-06-29 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_tel_legalentity_tel_main_and_more'),
        ('qpay', '0004_remove_qpaytx_seller_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyer_entity_choice',
            new_name='buyerEntity_choice',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyer_entityname',
            new_name='buyerEntity_entityname',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyer_email',
            new_name='buyerUser_email',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyer_personname',
            new_name='buyerUser_personname',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='seller_entityname',
            new_name='sellerEntity_entityname',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='seller_user_email',
            new_name='sellerUser_email',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='seller_user_personname',
            new_name='sellerUser_personname',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='buyer_entity',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='buyer_user',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='seller_entity',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='seller_user',
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='buyerEntity',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyerEntity_txs', to='accounts.legalentity', verbose_name='パートナー・エンティティ'),
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='buyerUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyerUser_txs', to=settings.AUTH_USER_MODEL, verbose_name='パートナー・ユーザー'),
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='sellerEntity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerEntity_txs', to='accounts.legalentity', verbose_name='ゲスト・エンティティ'),
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='sellerUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerUser_txs', to=settings.AUTH_USER_MODEL, verbose_name='ゲスト・ユーザー'),
        ),
    ]
