# Generated by Django 5.1.2 on 2026-03-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0004_alter_qpaytx_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpaytx',
            name='to_seller_amount',
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='advanced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='前払時点'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='advance_amount',
            field=models.IntegerField(default=0, verbose_name='前払予定額'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='advance_fee',
            field=models.IntegerField(default=0, verbose_name='前払手数料'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='exPayment_date',
            field=models.DateField(null=True, verbose_name='当初報酬日'),
        ),
    ]
