# Generated by Django 5.1.2 on 2025-06-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0005_rename_buyer_entity_choice_qpaytx_buyerentity_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyerEntity_entityname',
            new_name='buyerEntityname',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellerEntity_entityname',
            new_name='sellerEntityname',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='buyerEntity_choice',
        ),
    ]
