# Generated by Django 5.1.2 on 2026-04-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0005_remove_qpaytx_to_seller_amount_qpaytx_advanced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpaytx',
            name='transfer_amount',
            field=models.IntegerField(default=0, verbose_name='送金額'),
        ),
    ]
