# Generated by Django 5.1.2 on 2026-07-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0005_alter_qpaytx_clearinginfo_alter_qpaytx_sendbackinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpaytx',
            name='sendbackInfo',
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='sendbackInfo_admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminSendbackInfo_qpaytx', to='qpay.sendbackinfo', verbose_name='差戻情報（Qnee）'),
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='sendbackInfo_buyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyerSendbackInfo_qpaytx', to='qpay.sendbackinfo', verbose_name='差戻情報（パートナー）'),
        ),
    ]
