# Generated by Django 5.1.2 on 2026-05-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0006_qpaytx_transfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpaytx',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申請時点'),
        ),
    ]
