# Generated by Django 5.1.2 on 2025-07-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_is_approver_buyer_add_and_more'),
        ('qpay', '0006_rename_buyerentity_entityname_qpaytx_buyerentityname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyerEntityname',
            new_name='buyEntityname',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyerUser',
            new_name='buyUser',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyerUser_email',
            new_name='buyUser_email',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyerUser_personname',
            new_name='buyUser_personname',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellerEntity',
            new_name='sellEntity',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellerEntityname',
            new_name='sellEntityname',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellerUser',
            new_name='sellUser',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellerUser_email',
            new_name='sellUser_email',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellerUser_personname',
            new_name='sellUser_personname',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='buyerEntity',
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='buyEntity',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyEntity_txs', to='accounts.legalentity', verbose_name='パートナー・エンティティ'),
        ),
    ]
