# Generated by Django 5.1.2 on 2026-07-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0006_remove_qpaytx_sendbackinfo_qpaytx_sendbackinfo_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendbackinfo',
            name='status',
        ),
    ]
