# Generated by Django 5.1.2 on 2025-07-30 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_entities'),
        ('qpay', '0007_rename_buyerentityname_qpaytx_buyentityname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='buyEntity',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyEntity', to='accounts.legalentity', verbose_name='パートナー・エンティティ'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyUser', to=settings.AUTH_USER_MODEL, verbose_name='パートナー・ユーザー'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellEntity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellEntity', to='accounts.legalentity', verbose_name='ゲスト・エンティティ'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellUser', to=settings.AUTH_USER_MODEL, verbose_name='ゲスト・ユーザー'),
        ),
    ]
