# Generated by Django 5.1.2 on 2026-05-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0007_qpaytx_applied_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpaytx',
            name='advancePayment_date',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='transfer_amount',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='advance_amount',
            field=models.IntegerField(default=0, verbose_name='前払い予定額'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='advance_fee',
            field=models.IntegerField(default=0, verbose_name='前払い手数料'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='advanced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='前払い時点'),
        ),
    ]
