# Generated by Django 5.1.2 on 2026-07-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0007_remove_sendbackinfo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearinginfo',
            old_name='advanceTerm_YYYYMM',
            new_name='advancedTerm_YYYYMM',
        ),
        migrations.RemoveField(
            model_name='clearinginfo',
            name='clearedAmount',
        ),
        migrations.AddField(
            model_name='clearinginfo',
            name='amount_toBeCleared',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, null=True, verbose_name='清算必要額（円）'),
        ),
        migrations.AlterField(
            model_name='clearinginfo',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Seller Dropped'), (0, 'Unprocessed'), (1, 'Under Application'), (2, 'Buyer Pending'), (3, 'Buyer Approved'), (4, 'Qnee Pending'), (5, 'Qnee Payed'), (6, 'Buyer Payed'), (-3, 'Buyer Disapproved'), (-5, 'Qnee Disapproved')], default=1, verbose_name='清算状況'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='advance_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='前払い予定額'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='advance_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='前払い手数料'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='承認金額（円）'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='referral_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='ご報酬（紹介料）'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='requested_amount',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='ご申請金額（円）'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='total_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='合計手数料'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='送金額'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='transfer_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='振込手数料'),
        ),
    ]
