# Generated by Django 5.1.2 on 2025-07-30 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_entities_and_more'),
        ('qpay', '0008_alter_qpaytx_buyentity_alter_qpaytx_buyuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='buyEntity',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyEntity_qpaytxs', to='accounts.legalentity', verbose_name='パートナー・エンティティ'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyUser_qpaytxs', to=settings.AUTH_USER_MODEL, verbose_name='パートナー・ユーザー'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellEntity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellEntity_qpaytxs', to='accounts.legalentity', verbose_name='ゲスト・エンティティ'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellUser_qpaytxs', to=settings.AUTH_USER_MODEL, verbose_name='ゲスト・ユーザー'),
        ),
    ]
