# Generated by Django 5.1.2 on 2026-07-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0008_rename_advanceterm_yyyymm_clearinginfo_advancedterm_yyyymm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearinginfo',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='clearinginfo',
            name='cleared_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='清算日'),
        ),
    ]
