# Generated by Django 5.1.2 on 2025-08-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0009_alter_qpaytx_buyentity_alter_qpaytx_buyuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyEntityname',
            new_name='buyEntityName',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyUser_personname',
            new_name='buyUser_personName',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellEntityname',
            new_name='sellEntityName',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellUser_personname',
            new_name='sellUser_personName',
        ),
    ]
