# Generated by Django 5.1.2 on 2026-07-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0009_clearinginfo_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='txStatus',
            field=models.IntegerField(choices=[(-1, 'Seller Dropped'), (0, 'Unprocessed'), (1, 'Under Application'), (2, 'Buyer Pending'), (3, 'Buyer Approved'), (4, 'Qnee Pending'), (5, 'Qnee Payed'), (6, 'Buyer Payed'), (-3, 'Buyer Disapproved'), (-5, 'Qnee Disapproved')], default=0, verbose_name='処理状況 No'),
        ),
    ]
