# Generated by Django 5.1.2 on 2026-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0010_alter_qpaytx_txstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendbackinfo',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='メッセージ'),
        ),
    ]
