# Generated by Django 6.0.8 on 2026-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0011_alter_sendbackinfo_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpaytx',
            old_name='rejected_at',
            new_name='buyer_declined_at',
        ),
        migrations.AddField(
            model_name='qpaytx',
            name='qnee_declined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='謝絶時点'),
        ),
    ]
