# Generated by Django 6.0.8 on 2026-09-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0012_rename_rejected_at_qpaytx_buyer_declined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearinginfo',
            name='status_char',
            field=models.CharField(default='未清算', max_length=20, verbose_name='清算状況（文字）'),
        ),
        migrations.AlterField(
            model_name='clearinginfo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Tbd'), (2, 'Done')], default=1, verbose_name='清算状況'),
        ),
    ]
