# Generated by Django 5.1.2 on 2025-08-31 05:46

import django.core.validators
import django.db.models.deletion
import qpay.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_bankaccount_accountnumber_and_more'),
        ('qpay', '0014_alter_qpaytx_advance_amount_alter_qpaytx_advance_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='advance_amount',
            field=models.IntegerField(default=0, verbose_name='立替金額'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='advance_fee',
            field=models.IntegerField(default=0, verbose_name='立替手数料'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='advanced_payment_date',
            field=models.DateField(default=None, verbose_name='前払日'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='approved_amount',
            field=models.IntegerField(default=None, verbose_name='承認金額（円）'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='approved_at',
            field=models.DateTimeField(blank=True, default=None, verbose_name='承認時点'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyEntity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='buyEntity_qpaytxs', to='accounts.legalentity', verbose_name='パートナー・エンティティ'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyEntityName',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='パートナー・エンティティ名'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='buyUser_qpaytxs', to=settings.AUTH_USER_MODEL, verbose_name='パートナー・ユーザー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyUser_email',
            field=models.EmailField(default='', max_length=254, verbose_name='パートナー・メールアドレス'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyUser_personName',
            field=models.CharField(default='', max_length=150, verbose_name='パートナー・ユーザー名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='データ作成時点'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='evidence',
            field=models.FileField(default=None, upload_to=qpay.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])], verbose_name='ご報酬の証明（請求書など）'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='original_payment_date',
            field=models.DateField(default=None, verbose_name='報酬日'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='referral_fee',
            field=models.IntegerField(default=0, verbose_name='ご報酬（紹介料）'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='rejected_at',
            field=models.DateTimeField(blank=True, default=None, verbose_name='否認時点'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='requested_amount',
            field=models.IntegerField(default=None, verbose_name='ご申請金額（円）'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='requested_at',
            field=models.DateTimeField(default=None, verbose_name='ご申請時点'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellEntity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sellEntity_qpaytxs', to='accounts.legalentity', verbose_name='ゲスト・エンティティ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellEntityName',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='ゲスト・エンティティ名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sellUser_qpaytxs', to=settings.AUTH_USER_MODEL, verbose_name='ゲスト・ユーザー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellUser_email',
            field=models.EmailField(default='', max_length=254, verbose_name='ゲスト・メールアドレス'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellUser_personName',
            field=models.CharField(default='', max_length=150, verbose_name='ゲスト・ユーザー名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='to_seller_amount',
            field=models.IntegerField(default=0, verbose_name='振込金額'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='total_fee',
            field=models.IntegerField(default=0, verbose_name='合計手数料'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='transfer_fee',
            field=models.IntegerField(default=0, verbose_name='振込手数料'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='tx_status_char',
            field=models.CharField(default='承認待ち', max_length=20, verbose_name='処理状況'),
        ),
    ]
