# Generated by Django 5.1.2 on 2025-08-31 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_bankaccount_accountnumber_and_more'),
        ('qpay', '0015_alter_qpaytx_advance_amount_alter_qpaytx_advance_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='advanced_payment_date',
            field=models.DateField(verbose_name='前払日'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='approved_amount',
            field=models.IntegerField(verbose_name='承認金額（円）'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='approved_at',
            field=models.DateTimeField(blank=True, verbose_name='承認時点'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyEntity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyEntity_qpaytxs', to='accounts.legalentity', verbose_name='パートナー・エンティティ'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='original_payment_date',
            field=models.DateField(verbose_name='報酬日'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='rejected_at',
            field=models.DateTimeField(blank=True, verbose_name='否認時点'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='requested_amount',
            field=models.IntegerField(verbose_name='ご申請金額（円）'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='requested_at',
            field=models.DateTimeField(verbose_name='ご申請時点'),
        ),
    ]
