# Generated by Django 5.1.2 on 2025-09-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0016_alter_qpaytx_advanced_payment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpaytx',
            old_name='tx_status_char',
            new_name='txStatus_char',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='tx_status_int',
            new_name='txStatus_int',
        ),
    ]
