# Generated by Django 5.1.2 on 2025-09-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0017_rename_tx_status_char_qpaytx_txstatus_char_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpaytx',
            old_name='advanced_payment_date',
            new_name='advancePayment_date',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='original_payment_date',
            new_name='exPayment_date',
        ),
    ]
