# Generated by Django 5.1.2 on 2025-09-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0018_rename_advanced_payment_date_qpaytx_advancepayment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpaytx',
            old_name='buyUser_personName',
            new_name='buyUser_userName',
        ),
        migrations.RenameField(
            model_name='qpaytx',
            old_name='sellUser_personName',
            new_name='sellUser_userName',
        ),
    ]
