# Generated by Django 5.1.2 on 2025-10-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0019_rename_buyuser_personname_qpaytx_buyuser_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpaytx',
            name='buyUser_email',
        ),
        migrations.RemoveField(
            model_name='qpaytx',
            name='buyUser_userName',
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyUser_qpaytxs', to=settings.AUTH_USER_MODEL, verbose_name='パートナー・ユーザー'),
        ),
    ]
