# Generated by Django 5.1.2 on 2025-10-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0020_remove_qpaytx_buyuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='requested_at',
            field=models.DateTimeField(null=True, verbose_name='ご申請時点'),
        ),
    ]
