# Generated by Django 5.1.2 on 2025-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0021_alter_qpaytx_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='approved_amount',
            field=models.IntegerField(null=True, verbose_name='承認金額（円）'),
        ),
    ]
