# Generated by Django 5.1.2 on 2025-10-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0022_alter_qpaytx_approved_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='advancePayment_date',
            field=models.DateField(null=True, verbose_name='前払日'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='exPayment_date',
            field=models.DateField(null=True, verbose_name='報酬日'),
        ),
    ]
