# Generated by Django 5.1.2 on 2025-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0023_alter_qpaytx_advancepayment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認時点'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='否認時点'),
        ),
    ]
