# Generated by Django 5.1.2 on 2025-10-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0024_alter_qpaytx_approved_at_alter_qpaytx_rejected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpaytx',
            name='sellUser_email',
        ),
    ]
