# Generated by Django 5.1.2 on 2025-11-01 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_customuser_canreceive'),
        ('qpay', '0025_remove_qpaytx_selluser_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaytx',
            name='buyEntity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyEntity_txs', to='accounts.legalentity', verbose_name='パートナー・エンティティ'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='buyUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyUser_txs', to=settings.AUTH_USER_MODEL, verbose_name='パートナー・ユーザー'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellEntity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellEntity_txs', to='accounts.legalentity', verbose_name='ゲスト・エンティティ'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='sellUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellUser_txs', to=settings.AUTH_USER_MODEL, verbose_name='ゲスト・ユーザー'),
        ),
        migrations.AlterField(
            model_name='qpaytx',
            name='txStatus_char',
            field=models.CharField(default='未処理', max_length=20, verbose_name='処理状況'),
        ),
    ]
