# Generated by Django 5.1.2 on 2025-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpay', '0026_alter_qpaytx_buyentity_alter_qpaytx_buyuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpaytx',
            name='buyUser_userName',
            field=models.CharField(max_length=150, null=True, verbose_name='ゲスト・ユーザー名'),
        ),
    ]
