# Generated by Django 5.1.2 on 2026-06-09 21:14

import accounts.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holderName', models.CharField(default='', max_length=100, verbose_name='口座名義')),
                ('entity_id', models.IntegerField(blank=True, default=0, verbose_name='エンティティID')),
                ('bankCode', models.CharField(max_length=4, verbose_name='金融機関コード')),
                ('bankName', models.CharField(default='', max_length=25, verbose_name='金融機関名')),
                ('branchCode', models.CharField(default='', max_length=3, verbose_name='支店コード')),
                ('branchName', models.CharField(default='', max_length=25, verbose_name='支店名')),
                ('accountNumber', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message="口座番号は数字でご入力ください。ex '1234567'", regex='^[0-9]+$')], verbose_name='口座番号')),
                ('temporal_tx_id', models.IntegerField(blank=True, default=0, verbose_name='取引ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('userName', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='お名前')),
                ('userName_kana', models.CharField(blank=True, default='', max_length=50, verbose_name='お名前（カナ）')),
                ('firstName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名（First Name）')),
                ('lastName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='姓（Last Name）')),
                ('firstName_kana', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名のカナ（First Name）')),
                ('lastName_kana', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='姓のカナ（Last Name）')),
                ('type1', models.IntegerField(blank=True, choices=[(0, ''), (1, 'パートナー'), (2, 'ゲスト'), (3, 'Qnee')], null=True, verbose_name='属性1')),
                ('type2', models.IntegerField(blank=True, choices=[(0, ''), (1, '個人で利用'), (2, '会社でご利用')], default=0, verbose_name='属性2')),
                ('tel_user', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号')),
                ('zip_user', models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='部署名')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='役職名')),
                ('is_active', models.BooleanField(default=False, verbose_name='アクティブ')),
                ('addStatus', models.IntegerField(choices=[(1, 'Unproccessed'), (2, 'Approved'), (3, 'Disapproved')], default=1, verbose_name='参加承認')),
                ('addStatus_char', models.CharField(default='承認待ち', max_length=20, verbose_name='承認状況')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_admin', models.BooleanField(default=False)),
                ('canApproveAll', models.BooleanField(default=False, null=True, verbose_name='承認権限（全部）')),
                ('canApproveChg', models.BooleanField(default=False, null=True, verbose_name='承認権限（変更）')),
                ('canApproveQpay', models.BooleanField(default=False, null=True, verbose_name='承認権限（Qpay）')),
                ('canReceive', models.BooleanField(default=True, null=True, verbose_name='メール受信')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('joined_at', models.DateTimeField(null=True, verbose_name='加入日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.IntegerField(blank=True, choices=[(1, 'パートナー'), (2, 'ゲスト'), (3, 'Qnee')], default=1)),
                ('type2', models.IntegerField(blank=True, choices=[(1, '個人（法人組織でない）'), (2, '法人')], default=1)),
                ('entityName', models.CharField(default='', max_length=100, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='取引主体名')),
                ('representitive', models.CharField(blank=True, max_length=100, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='代表者名')),
                ('tel_entity', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号')),
                ('zip_entity', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号')),
                ('address1', models.CharField(max_length=30, null=True, verbose_name='都道府県・区市町村')),
                ('address2', models.CharField(max_length=20, null=True, verbose_name='〇丁目〇番〇号')),
                ('address3', models.CharField(max_length=30, null=True, verbose_name='建物・マンション名・部屋番号')),
                ('advance_fee_rate', models.DecimalField(decimal_places=10, default=0.06, max_digits=11)),
                ('referral_fee_rate', models.DecimalField(decimal_places=10, default=0.015, max_digits=11)),
                ('bankAccount_flag', models.IntegerField(default=0, verbose_name='口座設定フラグ')),
                ('membershipConsent_boolean', models.BooleanField(default=False, verbose_name='規約同意')),
                ('membershipConsent_at', models.DateTimeField(blank=True, null=True, verbose_name='規約同意の日時')),
                ('sourcingConsent_boolean', models.BooleanField(default=False, verbose_name='契約合意')),
                ('sourcingConsent_at', models.DateTimeField(blank=True, null=True, verbose_name='契約合意の日時')),
                ('bankAccount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.bankaccount', verbose_name='振込口座')),
            ],
        ),
        migrations.CreateModel(
            name='CorpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Default'), (2, 'Under Application'), (3, 'Pending'), (4, 'Approved'), (-4, 'Disapproved')], default=1, verbose_name='更新状況')),
                ('status_char', models.CharField(default='承認待ち', max_length=20, verbose_name='更新状況')),
                ('entityName', models.CharField(blank=True, default='', max_length=100, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='エンティティ名')),
                ('representitive', models.CharField(blank=True, max_length=100, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='代表者名')),
                ('tel_entity', models.CharField(blank=True, default='', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号')),
                ('zip_entity', models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号')),
                ('address1', models.CharField(max_length=30, null=True, verbose_name='都道府県・区市町村')),
                ('address2', models.CharField(max_length=20, null=True, verbose_name='〇丁目〇番〇号')),
                ('address3', models.CharField(max_length=30, null=True, verbose_name='建物・マンション名・部屋番号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='データ作成時点')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='データ更新時点')),
                ('evidence', models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])], verbose_name='更新情報の証明（登記簿謄本など）')),
                ('sendbackReason', models.CharField(blank=True, max_length=100, null=True, verbose_name='差戻理由')),
                ('sendbackMessage', models.TextField(blank=True, max_length=200, null=True, verbose_name='差戻理由')),
                ('applyUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('applyEntity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.legalentity', verbose_name='エンティティ')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_users', to='accounts.legalentity', verbose_name='取引主体'),
        ),
    ]
