# Generated by Django 5.1.2 on 2025-02-11 11:54

import accounts.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holdername', models.CharField(default='', max_length=150, null=True, verbose_name='口座名義')),
                ('entity_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='エンティティID')),
                ('bank_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='金融機関コード')),
                ('bank_name', models.CharField(blank=True, default=0, max_length=25, null=True, verbose_name='金融機関名')),
                ('branch_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='支店コード')),
                ('branch_name', models.CharField(blank=True, default=0, max_length=25, null=True, verbose_name='支店名')),
                ('accountNumber', models.CharField(default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="口座番号は数字でご入力ください。ex '1234567'", regex='^[0-9]+$')], verbose_name='口座番号')),
                ('temporal_tx_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='取引ID')),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.IntegerField(choices=[(1, '発注者'), (2, '受注者')], default=1)),
                ('type2', models.IntegerField(blank=True, choices=[(1, '個人（法人組織でない）'), (2, '法人')], default=1, null=True)),
                ('personname', models.CharField(default='', error_messages={'unique': 'A user with that username already exists'}, max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='個人名')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='メールアドレス')),
                ('tel', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='ハイフン「-」なしで数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号')),
                ('department', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='部署名')),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='役職名')),
                ('entityname', models.CharField(blank=True, default='', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='取引主体名')),
                ('postal_code', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('advance_fee_rate', models.DecimalField(decimal_places=10, default=0.06, max_digits=11)),
                ('referral_fee_rate', models.DecimalField(decimal_places=10, default=0.015, max_digits=11)),
                ('bank_account_flag', models.IntegerField(blank=True, default=0, null=True, verbose_name='口座設定フラグ')),
                ('is_consent_membership', models.BooleanField(default=False, verbose_name='規約同意')),
                ('date_consent_membership', models.DateTimeField(blank=True, null=True, verbose_name='規約同意の日時')),
                ('is_consent_outsource', models.BooleanField(default=False, verbose_name='契約合意')),
                ('date_consent_outsource', models.DateTimeField(blank=True, null=True, verbose_name='契約合意の日時')),
                ('date_joined', models.DateTimeField(blank=True, null=True, verbose_name='登録日')),
                ('bank_account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BankAccount_tx', to='accounts.bankaccount', verbose_name='振込口座')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('firstname', models.CharField(max_length=150, null=True, verbose_name='名（First Name）')),
                ('lastname', models.CharField(max_length=150, null=True, verbose_name='姓（Last Name）')),
                ('personname', models.CharField(max_length=150, null=True, verbose_name='お名前（個人）')),
                ('type1', models.IntegerField(blank=True, choices=[(1, '発注者'), (2, '受注者'), (3, 'その他')], default=1, null=True)),
                ('type2', models.IntegerField(blank=True, choices=[(1, '個人（法人組織でない）'), (2, '法人')], null=True)),
                ('entityname', models.CharField(blank=True, max_length=150, null=True, verbose_name='取引主体')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False, verbose_name='company')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_entity', to='accounts.legalentity', verbose_name='取引主体')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
