# Generated by Django 5.1.2 on 2026-03-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='type1',
            field=models.IntegerField(blank=True, choices=[(1, 'パートナー'), (2, 'ゲスト'), (3, 'Qnee')], default=1),
        ),
    ]
