# Generated by Django 5.1.2 on 2026-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='addStatus',
            field=models.IntegerField(choices=[(0, 'Unproccessed'), (1, 'Applied'), (2, 'Approved'), (3, 'Disapproved')], default=0, verbose_name='参加承認'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='sourcingConsent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='委託契約の合意日時'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='sourcingConsent_boolean',
            field=models.BooleanField(default=False, verbose_name='委託契約の合意'),
        ),
    ]
