# Generated by Django 5.1.2 on 2025-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type1',
            field=models.IntegerField(blank=True, choices=[(1, '発注者'), (2, '受注者'), (3, 'Qnee')], default=1, null=True),
        ),
    ]
