# Generated by Django 5.1.2 on 2026-06-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_username_customuser_personname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='personname',
        ),
    ]
