# Generated by Django 5.1.2 on 2025-05-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type1',
            field=models.IntegerField(blank=True, choices=[(1, 'パートナー'), (2, 'ゲスト'), (3, 'Qnee')], default=1, null=True, verbose_name='属性1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(1, '個人（法人組織でない）'), (2, '法人')], null=True, verbose_name='属性2'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='type1',
            field=models.IntegerField(choices=[(1, 'パートナー'), (2, 'ゲスト')], default=1),
        ),
    ]
