# Generated by Django 5.1.2 on 2026-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_legalentity_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='entityName',
            field=models.CharField(default='', max_length=100, verbose_name='取引主体名'),
        ),
    ]
