# Generated by Django 5.1.2 on 2026-03-14 12:52

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_legalentity_entityname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='entityName',
            field=models.CharField(default='', max_length=100, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='取引主体名'),
        ),
    ]
