# Generated by Django 5.1.2 on 2025-06-29 16:47

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_type1_alter_customuser_type2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalentity',
            old_name='tel',
            new_name='tel_main',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='entityname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='department',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='personname',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='title',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active1',
            field=models.BooleanField(default=False, verbose_name='アクティブ1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active2',
            field=models.BooleanField(default=False, verbose_name='アクティブ2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active3',
            field=models.BooleanField(default=False, verbose_name='アクティブ3'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approver_buyer_add',
            field=models.BooleanField(default=False, verbose_name='承認（参加）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approver_buyer_all',
            field=models.BooleanField(default=False, verbose_name='承認（全部）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approver_buyer_qpay',
            field=models.BooleanField(default=False, verbose_name='承認（Qpay）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approver_seller_add',
            field=models.BooleanField(default=False, verbose_name='承認（参加）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approver_seller_all',
            field=models.BooleanField(default=False, verbose_name='承認（全部）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approver_seller_qpay',
            field=models.BooleanField(default=False, verbose_name='承認（Qpay）'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='representitive',
            field=models.CharField(default='', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='代表者名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='アクティブ'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_entity', to='accounts.bankaccount', verbose_name='振込口座'),
        ),
        migrations.CreateModel(
            name='UserEntityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=150, null=True, verbose_name='お名前（個人）')),
                ('entityname', models.CharField(blank=True, default='', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='取引主体名')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='メールアドレス')),
                ('tel_direct', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='ハイフン「-」なしで数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号')),
                ('department', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='部署名')),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='役職名')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.legalentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='entities',
            field=models.ManyToManyField(null=True, related_name='entity_users', through='accounts.UserEntityRelation', to='accounts.legalentity', verbose_name='取引主体'),
        ),
    ]
