# Generated by Django 5.1.2 on 2026-06-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username_kana',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name_kana',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名前（カナ）'),
        ),
    ]
