# Generated by Django 5.1.2 on 2026-03-16 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_legalentity_entityname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joined_at',
            field=models.DateTimeField(null=True, verbose_name='加入日'),
        ),
    ]
