# Generated by Django 5.1.2 on 2026-06-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_username_kana_customuser_name_kana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='personalname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='name_kana',
            new_name='personalname_kana',
        ),
    ]
