# Generated by Django 5.1.2 on 2026-03-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_created_at_alter_customuser_joined_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='canApprove_add',
            new_name='canApproveAdd',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='canApprove_all',
            new_name='canApproveAll',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='canApprove_qpay',
            new_name='canApproveQpay',
        ),
    ]
