# Generated by Django 5.1.2 on 2025-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_admin_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_approver_buyer_add',
            field=models.BooleanField(default=False, verbose_name='パートナー側 承認（参加）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approver_buyer_all',
            field=models.BooleanField(default=False, verbose_name='パートナー側 承認（全部）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approver_buyer_qpay',
            field=models.BooleanField(default=False, verbose_name='パートナー側 承認（Qpay）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approver_seller_add',
            field=models.BooleanField(default=False, verbose_name='ゲスト側 承認（参加）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approver_seller_all',
            field=models.BooleanField(default=False, verbose_name='ゲスト側 承認（全部）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approver_seller_qpay',
            field=models.BooleanField(default=False, verbose_name='ゲスト側 承認（Qpay）'),
        ),
    ]
