# Generated by Django 5.1.2 on 2026-06-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_name_customuser_personalname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='personalname',
            new_name='personname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='personalname_kana',
            new_name='personname_kana',
        ),
    ]
