# Generated by Django 5.1.2 on 2025-07-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_is_approver_buyer_add_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank_code',
            new_name='BankCode',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank_name',
            new_name='BankName',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='branch_code',
            new_name='BranchCode',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='branch_name',
            new_name='BranchName',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='bank_account',
            new_name='BankAccount',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='bank_account_flag',
            new_name='BankAccount_flag',
        ),
    ]
