# Generated by Django 5.1.2 on 2026-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_canapprove_add_customuser_canapproveadd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approvedStatus_int',
            field=models.IntegerField(choices=[(1, 'Unproccessed'), (2, 'Approved'), (3, 'Disapproved')], default=1, verbose_name='参加承認'),
        ),
    ]
