# Generated by Django 5.1.2 on 2025-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_bank_code_bankaccount_bankcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entities',
            field=models.ManyToManyField(null=True, related_name='entities', through='accounts.UserEntityRelation', to='accounts.legalentity', verbose_name='取引主体'),
        ),
    ]
