# Generated by Django 5.1.2 on 2026-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_approvedstatus_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名（First Name）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstName_kana',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名のカナ（First Name）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='姓（Last Name）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastName_kana',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='姓のカナ（Last Name）'),
        ),
    ]
