# Generated by Django 5.1.2 on 2026-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_personalname_customuser_personname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='addStatus',
            field=models.IntegerField(choices=[(0, 'Unproccessed'), (1, 'Applied'), (3, 'Approved'), (-3, 'Disapproved')], default=0, verbose_name='参加承認'),
        ),
    ]
