# Generated by Django 5.1.2 on 2026-05-11 15:07

import accounts.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_firstname_customuser_firstname_kana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpInfo_TBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityName', models.CharField(default='', max_length=100, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='エンティティ名')),
                ('representitive', models.CharField(blank=True, max_length=100, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='代表者名')),
                ('tel_entity', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号')),
                ('zip_entity', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号')),
                ('address1', models.CharField(max_length=30, null=True, verbose_name='都道府県・区市町村')),
                ('address2', models.CharField(max_length=20, null=True, verbose_name='〇丁目〇番〇号')),
                ('address3', models.CharField(max_length=30, null=True, verbose_name='建物・マンション名・部屋番号')),
                ('evidence', models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])], verbose_name='会社情報の証明（登記情報など）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='データ作成時点')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.legalentity', verbose_name='エンティティ')),
            ],
        ),
    ]
