# Generated by Django 5.1.2 on 2026-06-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_addstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalentity',
            old_name='sourcingConsent_boolean',
            new_name='sourcingConsent',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='membershipConsent_boolean',
            new_name='termsConsent',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='membershipConsent_at',
            new_name='termsConsent_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='termsConsent',
            field=models.BooleanField(default=False, verbose_name='規約同意'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='termsConsent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='規約同意の日時'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bankAccount_flag',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='口座設定フラグ'),
        ),
    ]
