# Generated by Django 5.1.2 on 2025-07-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entities',
            field=models.ManyToManyField(null=True, related_name='users', through='accounts.UserEntityRelation', to='accounts.legalentity', verbose_name='取引主体'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='BankAccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.bankaccount', verbose_name='振込口座'),
        ),
    ]
