# Generated by Django 5.1.2 on 2026-06-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_sourcingconsent_boolean_legalentity_sourcingconsent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='entity_id',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='entity',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.legalentity', verbose_name='取引主体'),
        ),
    ]
