# Generated by Django 5.1.2 on 2025-08-18 12:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_entities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='entities',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='postal_code',
            new_name='postalCode_entity',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='tel_main',
            new_name='tel_entity',
        ),
        migrations.AddField(
            model_name='customuser',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_users', to='accounts.legalentity', verbose_name='取引主体'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postalCode_entity',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel_user',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='ハイフン「-」なしで数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号'),
        ),
        migrations.DeleteModel(
            name='UserEntityRelation',
        ),
    ]
