# Generated by Django 5.1.2 on 2026-05-11 15:10

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_corpinfo_tbu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpinfo_tbu',
            name='evidence',
            field=models.FileField(default=True, null=True, upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])], verbose_name='更新情報の証明（登記簿謄本など）'),
        ),
        migrations.AlterField(
            model_name='corpinfo_tbu',
            name='zip_entity',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号'),
        ),
    ]
