# Generated by Django 5.1.2 on 2026-07-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_bankaccount_entity_id_bankaccount_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='temporal_tx_id',
        ),
    ]
