# Generated by Django 5.1.2 on 2025-08-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_entities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='BankCode',
            new_name='bankCode',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='BankName',
            new_name='bankName',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='BranchCode',
            new_name='branchCode',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='BranchName',
            new_name='branchName',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='holdername',
            new_name='holderName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='personname',
            new_name='personName',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='BankAccount',
            new_name='bankAccount',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='BankAccount_flag',
            new_name='bankAccount_flag',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='entityname',
            new_name='entityName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active3',
        ),
    ]
