# Generated by Django 5.1.2 on 2026-05-11 15:58

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_corpinfo_tbu_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpinfo_tbu',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.legalentity', verbose_name='エンティティ'),
        ),
        migrations.AlterField(
            model_name='corpinfo_tbu',
            name='entityName',
            field=models.CharField(blank=True, default='', max_length=100, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='エンティティ名'),
        ),
        migrations.AlterField(
            model_name='corpinfo_tbu',
            name='tel_entity',
            field=models.CharField(blank=True, default='', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号'),
        ),
    ]
