# Generated by Django 6.0.8 on 2026-09-23 10:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_bankaccount_temporal_tx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpinfo',
            name='entityname',
            field=models.CharField(blank=True, default='', max_length=100, null=True, validators=[accounts.models.CustomUnicodeUsernameValidator()], verbose_name='エンティティ名'),
        ),
        migrations.AlterField(
            model_name='corpinfo',
            name='representitive',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[accounts.models.CustomUnicodeUsernameValidator()], verbose_name='代表者名'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='entityname',
            field=models.CharField(default='', max_length=100, validators=[accounts.models.CustomUnicodeUsernameValidator()], verbose_name='取引主体名'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='representitive',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[accounts.models.CustomUnicodeUsernameValidator()], verbose_name='代表者名'),
        ),
    ]
