# Generated by Django 5.1.2 on 2026-05-11 16:41

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_corpinfo_tbu_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpinfo_tbu',
            name='evidence',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'pdf'])], verbose_name='更新情報の証明（登記簿謄本など）'),
        ),
    ]
