# Generated by Django 5.1.2 on 2025-08-20 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_bankcode_bankaccount_bankcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='名（First Name）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='姓（Last Name）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_user',
            field=models.CharField(default='', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='ハイフン「-」なしで数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号'),
        ),
    ]
