# Generated by Django 5.1.2 on 2025-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_firstname_alter_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_approver_buyer_add',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approver_buyer_all',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approver_buyer_qpay',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approver_seller_add',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approver_seller_all',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approver_seller_qpay',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approver_add',
            field=models.BooleanField(default=False, verbose_name='承認権限（参加）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approver_all',
            field=models.BooleanField(default=False, verbose_name='承認権限（全部）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approver_qpay',
            field=models.BooleanField(default=False, verbose_name='承認権限（Qpay）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=150, null=True, verbose_name='名（First Name）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=150, null=True, verbose_name='姓（Last Name）'),
        ),
    ]
