# Generated by Django 5.1.2 on 2026-05-12 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_corpinfo_tbu_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpinfo_tbu',
            name='applyUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
