# Generated by Django 5.1.2 on 2025-08-31 03:14

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customuser_is_approver_buyer_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='', max_length=150, verbose_name='名（First Name）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='', max_length=150, verbose_name='姓（Last Name）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='personName',
            field=models.CharField(default='', max_length=150, verbose_name='お名前（個人）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_user',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='ハイフン「-」なしで数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type1',
            field=models.IntegerField(choices=[(1, 'パートナー'), (2, 'ゲスト'), (3, 'Qnee')], default=1, verbose_name='属性1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type2',
            field=models.IntegerField(choices=[(1, '個人（法人組織でない）'), (2, '法人')], verbose_name='属性2'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='entityName',
            field=models.CharField(default='', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='取引主体名'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='representitive',
            field=models.CharField(default='', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='代表者名'),
        ),
    ]
