# Generated by Django 5.1.2 on 2026-05-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_approvedstatus_int_customuser_addstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpinfo',
            name='applyUserName',
        ),
        migrations.RemoveField(
            model_name='corpinfo',
            name='is_primary',
        ),
    ]
