# Generated by Django 5.1.2 on 2025-08-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_firstname_alter_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='holderName',
            field=models.CharField(default='', max_length=150, verbose_name='口座名義'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='名（First Name）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='姓（Last Name）'),
        ),
    ]
