# Generated by Django 5.1.2 on 2025-08-31 05:33

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_bankaccount_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='accountNumber',
            field=models.CharField(default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="口座番号は数字でご入力ください。ex '1234567'", regex='^[0-9]+$')], verbose_name='口座番号'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bankCode',
            field=models.CharField(max_length=4, null=True, verbose_name='金融機関コード'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bankName',
            field=models.CharField(default='', max_length=25, null=True, verbose_name='金融機関名'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branchCode',
            field=models.CharField(default='', max_length=3, null=True, verbose_name='支店コード'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branchName',
            field=models.CharField(default='', max_length=25, null=True, verbose_name='支店名'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='entity_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='エンティティID'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='holderName',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='口座名義'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='temporal_tx_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='取引ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='名（First Name）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='姓（Last Name）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='personName',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='お名前（個人）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postalCode_entity',
            field=models.CharField(blank=True, default='', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_user',
            field=models.CharField(default='', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='ハイフン「-」なしで数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type1',
            field=models.IntegerField(choices=[(1, 'パートナー'), (2, 'ゲスト'), (3, 'Qnee')], default=1, null=True, verbose_name='属性1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type2',
            field=models.IntegerField(choices=[(1, '個人（法人組織でない）'), (2, '法人')], null=True, verbose_name='属性2'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bankAccount_flag',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='口座設定フラグ'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='date_consent_membership',
            field=models.DateTimeField(blank=True, null=True, verbose_name='規約同意の日時'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='date_consent_outsource',
            field=models.DateTimeField(blank=True, null=True, verbose_name='契約合意の日時'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='entityName',
            field=models.CharField(blank=True, default='', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='取引主体名'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='postalCode_entity',
            field=models.CharField(blank=True, default='', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='representitive',
            field=models.CharField(blank=True, default='', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='代表者名'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='tel_entity',
            field=models.CharField(default='', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='ハイフン「-」なしで数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='type1',
            field=models.IntegerField(blank=True, choices=[(1, 'パートナー'), (2, 'ゲスト')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(1, '個人（法人組織でない）'), (2, '法人')], default=1, null=True),
        ),
    ]
