# Generated by Django 5.1.2 on 2025-09-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_bankaccount_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(1, '個人（法人組織でない）'), (2, '法人')], verbose_name='属性2'),
        ),
    ]
