# Generated by Django 5.1.2 on 2025-09-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_type2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entity_users', to='accounts.legalentity', verbose_name='取引主体'),
        ),
    ]
