# Generated by Django 5.1.2 on 2025-09-06 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_legalentity_entityname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='postalCode_entity',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
    ]
