# Generated by Django 5.1.2 on 2025-09-06 23:13

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_legalentity_postalcode_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='entityName',
            field=models.CharField(default='', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='取引主体名'),
        ),
    ]
