# Generated by Django 5.1.2 on 2025-09-07 06:52

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_legalentity_entityname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_approver_add',
            new_name='canApprove_add',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_approver_all',
            new_name='canApprove_all',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_approver_qpay',
            new_name='canApprove_qpay',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='approvedStatus_char',
            field=models.CharField(default='承認待ち', max_length=20, verbose_name='承認状況'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approvedStatus_int',
            field=models.IntegerField(choices=[(1, 'Unproccessed'), (2, 'Approved'), (3, 'Disapproved')], default=1, verbose_name='承認状況 No'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bankAccount_flag',
            field=models.IntegerField(default=0, verbose_name='口座設定フラグ'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='entityName',
            field=models.CharField(default='', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='取引主体名'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='representitive',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='代表者名'),
        ),
    ]
