# Generated by Django 5.1.2 on 2025-09-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_rename_is_approver_add_customuser_canapprove_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='bankAccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.bankaccount', verbose_name='振込口座'),
        ),
    ]
