# Generated by Django 5.1.2 on 2025-09-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_customuser_type1_alter_customuser_type2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='date_consent_membership',
            field=models.DateTimeField(blank=True, null=True, verbose_name='規約同意の日時'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='date_consent_outsource',
            field=models.DateTimeField(blank=True, null=True, verbose_name='契約合意の日時'),
        ),
    ]
