# Generated by Django 5.1.2 on 2025-09-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_legalentity_date_consent_membership_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joined',
            new_name='joined_at',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='date_joined',
            new_name='joined_at',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='date_consent_membership',
            new_name='membershipConsent_at',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='is_consent_membership',
            new_name='membershipConsent_boolean',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='date_consent_outsource',
            new_name='sourcingConsent_at',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='is_consent_outsource',
            new_name='sourcingConsent_boolean',
        ),
    ]
