# Generated by Django 5.1.2 on 2025-09-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_rename_date_joined_customuser_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日'),
        ),
    ]
