# Generated by Django 5.1.2 on 2025-09-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_legalentity_joined_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='postalCode_entity',
            new_name='postalCode_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='部署名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='役職名'),
        ),
    ]
