# Generated by Django 5.1.2 on 2025-09-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_postalcode_entity_customuser_postalcode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='canApprove_add',
            field=models.BooleanField(default=False, null=True, verbose_name='承認権限（参加）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='canApprove_all',
            field=models.BooleanField(default=False, null=True, verbose_name='承認権限（全部）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='canApprove_qpay',
            field=models.BooleanField(default=False, null=True, verbose_name='承認権限（Qpay）'),
        ),
    ]
