# Generated by Django 5.1.2 on 2025-09-28 07:59

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_customuser_canapprove_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='personName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postalCode_user',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='postalCode_entity',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userName',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='お名前'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userName_kana',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='お名前（カナ）'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_user',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='address1',
            field=models.CharField(max_length=100, null=True, verbose_name='都道府県・区市町村・丁目番地'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='address2',
            field=models.CharField(max_length=100, null=True, verbose_name='建物名・部屋番号'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='zip_entity',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='holderName',
            field=models.CharField(default='', max_length=100, verbose_name='口座名義'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='部署名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_user',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='役職名'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='entityName',
            field=models.CharField(default='', max_length=100, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='取引主体名'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='representitive',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='代表者名'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='tel_entity',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='数字のみご入力下さい（最大15桁）\u3000例：09012345678.', regex='^[0-9０-９ー―－‐₋⁻-]+$')], verbose_name='電話番号'),
        ),
    ]
