# Generated by Django 5.1.2 on 2025-09-30 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zip_user',
            field=models.CharField(blank=True, default='', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号'),
        ),
    ]
