# Generated by Django 5.1.2 on 2025-09-30 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_customuser_zip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zip_user',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='zip_entity',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="7桁の数字のみご入力ください\u3000例: '1234567'", regex='^[0-9０-９]{7}+$')], verbose_name='郵便番号'),
        ),
    ]
