# Generated by Django 5.1.2 on 2025-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_customuser_zip_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type2',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, '個人で利用'), (2, '会社でご利用')], default=0, verbose_name='属性2'),
        ),
    ]
