# Generated by Django 5.1.2 on 2025-10-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_customuser_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='canReceive',
            field=models.BooleanField(default=True, null=True, verbose_name='メール受信'),
        ),
    ]
