# Generated by Django 5.1.2 on 2026-02-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_customuser_canreceive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='address1',
            field=models.CharField(max_length=30, null=True, verbose_name='都道府県・区市町村'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='address2',
            field=models.CharField(max_length=30, null=True, verbose_name='建物・マンション名・部屋番号'),
        ),
    ]
