# Generated by Django 5.1.2 on 2026-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_legalentity_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='address3',
            field=models.CharField(max_length=30, null=True, verbose_name='建物・マンション名・部屋番号'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='address2',
            field=models.CharField(max_length=20, null=True, verbose_name='〇丁目〇番〇号'),
        ),
    ]
