# Generated by Django 5.1.2 on 2026-02-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_legalentity_address3_alter_legalentity_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='joined_at',
        ),
    ]
