# Generated by Django 5.1.2 on 2026-02-28 04:43

import django.db.models.deletion
import django.utils.timezone
import send.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=50, verbose_name='メルアドリスト名')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('buyEntity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.legalentity', verbose_name='パートナー')),
                ('createUser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='IndvAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_id', models.CharField(max_length=6)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('addList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='send.addlist')),
            ],
        ),
        migrations.CreateModel(
            name='ServInfoMailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='モデル生成日時')),
                ('sent_at', models.DateTimeField(null=True, verbose_name='送信日時')),
                ('addList', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='send.addlist', verbose_name='適用アドレスリスト')),
                ('buyEntity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.legalentity', verbose_name='パートナー')),
                ('sendUser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='ServInfoMailSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeatOnOff', models.CharField(default='on', max_length=5, verbose_name='する・しない')),
                ('startDate', models.DateField(null=True, verbose_name='開始日')),
                ('interval', models.IntegerField(default=2, null=True, verbose_name='間隔')),
                ('dayOfMonth', models.IntegerField(default=1, null=True, verbose_name='月の〇日')),
                ('json_sendMonth', models.JSONField(default=send.models.getInitDict_sendMonth, null=True, verbose_name='配信月')),
                ('json_sendDay', models.JSONField(default=send.models.getInitDict_sendDay, null=True, verbose_name='配信日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('addList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='send.addlist')),
                ('buyEntity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyentity_users', to='accounts.legalentity', verbose_name='ゲスト・ユーザー')),
            ],
        ),
    ]
