# Generated by Django 5.1.2 on 2025-11-01 15:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0040_customuser_canreceive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]


