# Generated by Django 5.1.2 on 2026-03-01 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinfomaillog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='モデル生成日時'),
        ),
    ]
