# Generated by Django 5.1.2 on 2026-02-08 08:58

import django.db.models.deletion
import django.utils.timezone
import send.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0040_customuser_canreceive'),
        ('send', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServInfoMailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendList', models.JSONField(default=dict, null=True, verbose_name='送信先')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='送信日時')),
                ('buyEntity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_sndEntitys', to='accounts.legalentity', verbose_name='パートナー')),
                ('sendUser', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_sndUsers', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='ServInfoMailSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeatOnOff', models.IntegerField(default=1, verbose_name='する・しない')),
                ('startDate', models.DateField(verbose_name='開始日')),
                ('interval', models.IntegerField(default=2, verbose_name='間隔')),
                ('dayOfMonth', models.IntegerField(default=1, verbose_name='月の〇日')),
                ('json_sendMonth', models.JSONField(default=send.models.getInitDict_sendMonth, verbose_name='配信月')),
                ('json_sendDay', models.JSONField(default=send.models.getInitDict_sendDay, verbose_name='配信日')),
                ('exclusions', models.JSONField(default=dict, null=True, verbose_name='除外アドレス')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('buyEntity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyentity_users', to='accounts.legalentity', verbose_name='ゲスト・ユーザー')),
            ],
        ),
    ]
