# Generated by Django 5.1.2 on 2026-03-01 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_alter_servinfomaillog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='作成日時'),
        ),
    ]
