# Generated by Django 5.1.2 on 2026-02-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinfomailsets',
            name='repeatOnOff',
            field=models.CharField(default='on', max_length=5, verbose_name='する・しない'),
        ),
    ]
