# Generated by Django 5.1.2 on 2026-02-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_customuser_canreceive'),
        ('send', '0003_alter_servinfomailsets_repeatonoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinfomailsets',
            name='buyEntity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyentity_users', to='accounts.legalentity', verbose_name='ゲスト・ユーザー'),
        ),
    ]
