# Generated by Django 5.1.2 on 2026-02-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0004_alter_servinfomailsets_buyentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinfomailsets',
            name='dayOfMonth',
            field=models.IntegerField(default=1, null=True, verbose_name='月の〇日'),
        ),
        migrations.AlterField(
            model_name='servinfomailsets',
            name='interval',
            field=models.IntegerField(default=2, null=True, verbose_name='間隔'),
        ),
        migrations.AlterField(
            model_name='servinfomailsets',
            name='startDate',
            field=models.DateField(null=True, verbose_name='開始日'),
        ),
    ]
