# Generated by Django 5.1.2 on 2026-03-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0004_alter_addlist_listname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlist',
            name='listName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='メルアドリスト名'),
        ),
    ]
