# Generated by Django 5.1.2 on 2026-02-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0005_alter_servinfomailsets_dayofmonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinfomailsets',
            name='json_sendDay',
            field=models.JSONField(verbose_name='配信日'),
        ),
        migrations.AlterField(
            model_name='servinfomailsets',
            name='json_sendMonth',
            field=models.JSONField(verbose_name='配信月'),
        ),
    ]
