# Generated by Django 5.1.2 on 2026-03-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0006_alter_addlist_listname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servinfomailsets',
            name='addList',
        ),
        migrations.AddField(
            model_name='servinfomailsets',
            name='appliedList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='send.addlist'),
        ),
    ]
