# Generated by Django 5.1.2 on 2026-03-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0007_remove_servinfomailsets_addlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlist',
            name='listName',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='メルアドリスト名'),
        ),
    ]
