# Generated by Django 5.1.2 on 2026-02-14 02:04

import send.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0007_alter_servinfomailsets_json_sendday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinfomailsets',
            name='json_sendDay',
            field=models.JSONField(default=send.models.getInitDict_sendDay, null=True, verbose_name='配信日'),
        ),
        migrations.AlterField(
            model_name='servinfomailsets',
            name='json_sendMonth',
            field=models.JSONField(default=send.models.getInitDict_sendMonth, null=True, verbose_name='配信月'),
        ),
    ]
