# Generated by Django 5.1.2 on 2026-03-15 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_legalentity_entityname'),
        ('send', '0008_alter_addlist_listname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServInfoMailLog',
            new_name='InvitationLog',
        ),
        migrations.RenameModel(
            old_name='ServInfoMailSets',
            new_name='InvitationSets',
        ),
    ]
