# Generated by Django 5.1.2 on 2026-02-21 11:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0008_alter_servinfomailsets_json_sendday_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servinfomaillog',
            name='sendList',
        ),
        migrations.AddField(
            model_name='servinfomaillog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='モデル生成日時'),
        ),
        migrations.AddField(
            model_name='servinfomaillog',
            name='mailingList',
            field=models.JSONField(null=True, verbose_name='送信先'),
        ),
        migrations.AlterField(
            model_name='servinfomaillog',
            name='sendUser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_sndUsers', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='servinfomaillog',
            name='sent_at',
            field=models.DateTimeField(null=True, verbose_name='送信日時'),
        ),
    ]
