# Generated by Django 5.1.2 on 2026-02-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0009_remove_servinfomaillog_sendlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servinfomaillog',
            name='mailingList',
        ),
        migrations.CreateModel(
            name='AddrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_id', models.CharField(max_length=6)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('logLink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='send.servinfomaillog')),
            ],
        ),
    ]
