# Generated by Django 5.1.2 on 2026-03-16 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0009_rename_servinfomaillog_invitationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationsets',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='addlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
    ]
