# Generated by Django 5.1.2 on 2026-02-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0010_remove_servinfomaillog_mailinglist_addrprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrprofile',
            name='data',
        ),
        migrations.AddField(
            model_name='addrprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addrprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
