# Generated by Django 5.1.2 on 2026-02-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0011_remove_addrprofile_data_addrprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrprofile',
            name='sent_at',
            field=models.DateTimeField(null=True, verbose_name='送信日時'),
        ),
    ]
