# Generated by Django 5.1.2 on 2026-02-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0012_addrprofile_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrprofile',
            name='repeat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servinfomaillog',
            name='repeat',
            field=models.BooleanField(default=True),
        ),
    ]
